# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "integration-tests-initial" ]
  pull_request:
    branches: [ "integration-tests-initial" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Compose Docker Containers"
  compose-docker-containers:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install python testing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pytest psycopg2
      
      - name: Setup Test environment
        working-directory: ./test
        run: |
          ./setup-test-env.sh

      - name: Run Tests
        working-directory: ./test
        run: |
          ./run-tests.sh